### ISSUE TITLE
Module implementation tracking

### ISSUE THREAD

**Issue by roj1512** [xorgram/xor#4]
This issue is for tracking and discussing the implementation of the stable built-in modules of the userbot.

# Modules to Get Implemented

- [x] admin: Administer chats easily

# External Plugin Ideas

- [ ] afk: Tell others you are AFK
- [x] paste: Text & file pasting to services like spaceb.in nekobin.com etc

**Comment by ArnabXD** [comment]
I am taking admin module part

**Comment by roj1512** [comment]
Super!

**Comment by roj1512** [comment]
We will continue discussing this in the groups. Closing.

**Comment by ArnabXD** [comment]
Anyone having plugin suggestions/requests, go to [@xortest](https://telegram.dog/xortest).
